//"use strict"
var zakrepi = angular.module('zakrepi',[]);

/*zakrepi.controller('HomeProductsCtrl', function($scope, $http){
	/*$http.get('content/home-products.json').success(function(data){
		$scope.products = data;
		console.log($scope.products);
	});*//*
	$scope.products = [
		{
			"id": 1,
			"name": "3D Ultra HD Led телевизор Sony KD-79X9005B",
			"image": "images/content/products/product-1.jpg",
			"rating": 3,
			"reviews": 4,
			"oldprice": 499000,
			"price": 449000,
			"today": true,
			"new": false,
			"bestseller": false,
		},
		{
			"id": 2,
			"name": "Игровая приставка Sony PS4 500GB Black",
			"image": "images/content/products/product-2.jpg",
			"rating": 4,
			"reviews": 13,
			"oldprice": "",
			"price": 27990,
			"today": true,
			"new": false,
			"bestseller": false,
		},
		{
			"id": 3,
			"name": "Овощерезка Moulinex Dj905",
			"image": "images/content/products/product-3.jpg",
			"rating": 1,
			"reviews": 2,
			"oldprice": "",
			"price": 14000,
			"today": true,
			"new": false,
			"bestseller": false,
		},
		{
			"id": 4,
			"name": "Фотоаппарат зеркальный Nikon D3200 kit 18-55VRII Black",
			"image": "images/content/products/product-4.jpg",
			"rating": 4,
			"reviews": 5,
			"oldprice": "",
			"price": 24000,
			"today": true,
			"new": false,
			"bestseller": false,
		},
		{
			"id": 5,
			"name": "Ноутбук Lenovo IdeaPad G5030 (80G000FLRK)",
			"image": "images/content/products/product-5.jpg",
			"rating": 3,
			"reviews": 16,
			"oldprice": 21000,
			"price": 19790,
			"today": true,
			"new": true,
			"bestseller": true,
		},
		{
			"id": 6,
			"name": "Видеокамера экшн GoPro Hero 4 Black Edition Motosport",
			"image": "images/content/products/product-6.jpg",
			"rating": 4,
			"reviews": 117,
			"oldprice": "",
			"price": 29990,
			"today": true,
			"new": true,
			"bestseller": false,
		},
		{
			"id": 7,
			"name": "Автомобильный радар Neoline X-COP 8500",
			"image": "images/content/products/product-7.jpg",
			"rating": 1,
			"reviews": 7,
			"oldprice": "",
			"price": 7600,
			"today": true,
			"new": true,
			"bestseller": true,
		},
		{
			"id": 8,
			"name": "Фотоэпилятор Remington IPL600F",
			"image": "images/content/products/product-8.jpg",
			"rating": 4,
			"reviews": 2,
			"oldprice": "",
			"price": 24990,
			"today": true,
			"new": true,
			"bestseller": false,
		},
		{
			"id": 9,
			"name": "Смартфон Asus Zenfon 4 White",
			"image": "images/content/products/product-9.jpg",
			"rating": 3,
			"reviews": 64,
			"oldprice": 7990,
			"price": 6490,
			"today": false,
			"new": true,
			"bestseller": true,
		},
		{
			"id": 10,
			"name": "Посудомоечная машина (60 см) Siemens SpeedMatic SN26M285RU",
			"image": "images/content/products/product-10.jpg",
			"rating": 4,
			"reviews": 43,
			"oldprice": "",
			"price": 55390,
			"today": false,
			"new": true,
			"bestseller": true,
		},
		{
			"id": 11,
			"name": "Планшет Apple iPad Air 2 Wi-Fi + Cellular 16Gb Black",
			"image": "images/content/products/product-11.jpg",
			"rating": 5,
			"reviews": 237,
			"oldprice": "",
			"price": 32000,
			"today": false,
			"new": false,
			"bestseller": true,
		},
		{
			"id": 12,
			"name": "Кофемашина капсульного типа Nespresso De Longhi EN550.B",
			"image": "images/content/products/product-12.jpg",
			"rating": 4,
			"reviews": 55,
			"oldprice": "",
			"price": 27790,
			"today": false,
			"new": false,
			"bestseller": true,
		},
	];
});*/
zakrepi.controller('CatalogProductsCtrl', function($scope, $http){
	/*$http.get('content/catalog-products.json').success(function(data){
		$scope.products = data;
		//console.log($scope.products);
	});*/
	$scope.orderProp = 'id';
	$scope.products = [
		{
			"id": 1,
			"name": "Гайковерт ударный Makita 6271DWPE",
			"image": "images/content/products/cataloge-product-1.jpg",
			"rating": 2,
			"reviews": 13,
			"oldprice": "",
			"price": 7299,
			"quantity": 1,
		},
		{
			"id": 2,
			"name": "Гайковерт ударный Makita 6951",
			"image": "images/content/products/cataloge-product-2.jpg",
			"rating": 4,
			"reviews": 8,
			"oldprice": "",
			"price": 8599,
			"quantity": 2,
		},
		{
			"id": 3,
			"name": "Гайковерт ударный AEG BSS 18C 12Z-0",
			"image": "images/content/products/cataloge-product-3.jpg",
			"rating": 5,
			"reviews": 3,
			"oldprice": 6600,
			"price": 6060,
			"quantity": 3,
		},
		{
			"id": 4,
			"name": "Гайковерт угловой Makita 6766D",
			"image": "images/content/products/cataloge-product-4.jpg",
			"rating": 2,
			"reviews": 11,
			"oldprice": "",
			"price": 9990,
			"quantity": 10,
		},
		{
			"id": 5,
			"name": "Гайковерт угловой  Milwaukee M12 IR",
			"image": "images/content/products/cataloge-product-5.jpg",
			"rating": 4,
			"reviews": 1,
			"oldprice": "",
			"price": 12395,
			"quantity": 1,
		},
		{
			"id": 6,
			"name": "Гайковерт угловой FEIN SCW 16-6",
			"image": "images/content/products/cataloge-product-6.jpg",
			"rating": 5,
			"reviews": 3,
			"oldprice": 26060,
			"price": 19060,
			"quantity": 25,
		},
		{
			"id": 7,
			"name": "Гайковерт ударный Makita 6271DWPE",
			"image": "images/content/products/cataloge-product-1.jpg",
			"rating": 2,
			"reviews": 13,
			"oldprice": "",
			"price": 7299,
			"quantity": 1,
		},
		{
			"id": 8,
			"name": "Гайковерт ударный Makita 6951",
			"image": "images/content/products/cataloge-product-2.jpg",
			"rating": 4,
			"reviews": 8,
			"oldprice": "",
			"price": 8599,
			"quantity": 2,
		},
		{
			"id": 9,
			"name": "Гайковерт ударный AEG BSS 18C 12Z-0",
			"image": "images/content/products/cataloge-product-3.jpg",
			"rating": 5,
			"reviews": 3,
			"oldprice": 6600,
			"price": 6060,
			"quantity": 3,
		},
		{
			"id": 10,
			"name": "Гайковерт угловой Makita 6766D",
			"image": "images/content/products/cataloge-product-4.jpg",
			"rating": 2,
			"reviews": 11,
			"oldprice": "",
			"price": 9990,
			"quantity": 10,
		},
		{
			"id": 11,
			"name": "Гайковерт угловой  Milwaukee M12 IR",
			"image": "images/content/products/cataloge-product-5.jpg",
			"rating": 4,
			"reviews": 1,
			"oldprice": "",
			"price": 12395,
			"quantity": 1,
		},
		{
			"id": 12,
			"name": "Гайковерт угловой FEIN SCW 16-6",
			"image": "images/content/products/cataloge-product-6.jpg",
			"rating": 5,
			"reviews": 3,
			"oldprice": 26060,
			"price": 19060,
			"quantity": 25,
		},
	];
});